# -*- coding: utf-8 -*-
"""PA_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OvZ2EXV3QAWENDea-U0sGCTa2GEPpy15

**Importing Libararies**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay, log_loss

from xgboost import XGBClassifier

df = pd.read_csv("/content/loan_approval_dataset.csv")

df.head()

"""**Columns cleaning**"""

df.columns = df.columns.str.strip()

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

df.head()

"""**Data set checking**"""

print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns)

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nLoan status counts:")
print(df["loan_status"].value_counts())

"""**Possible Negative/Outliers**"""

print("Negative values in residential_assets_value:")
print(df[df["residential_assets_value"] < 0])

"""**Loan Status distribution**"""

df["loan_status"].value_counts().plot(kind="bar")
plt.title("Loan Approval Status Distribution")
plt.xlabel("Loan Status")
plt.ylabel("Number of Applications")
plt.show()

"""**CIBIL Score distribution**"""

df["cibil_score"].plot(kind="hist", bins=20)
plt.title("Distribution of CIBIL Score")
plt.xlabel("CIBIL Score")
plt.ylabel("Frequency")
plt.show()

"""**Income vs Loan Amount**"""

plt.scatter(df["income_annum"], df["loan_amount"])
plt.title("Income vs Loan Amount")
plt.xlabel("Annual Income")
plt.ylabel("Loan Amount")
plt.show()

"""**Average CIBIL score by loan status**"""

df.groupby("loan_status")["cibil_score"].mean().plot(kind="bar")
plt.title("Average CIBIL Score by Loan Status")
plt.xlabel("Loan Status")
plt.ylabel("Average CIBIL Score")
plt.show()

"""**Encode categorical columns**"""

data = df.copy()

data["education"] = data["education"].map({
    "Graduate": 1,
    "Not Graduate": 0
})

data["self_employed"] = data["self_employed"].map({
    "Yes": 1,
    "No": 0
})

data["loan_status"] = data["loan_status"].map({
    "Approved": 1,
    "Rejected": 0
})

data.head()

X = data.drop(["loan_id", "loan_status"], axis=1)
y = data["loan_status"]

print(X.head())
print(y.head())

"""**Train-test split**"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

"""**Scaledata for SVM**"""

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""**Train SVM Model**"""

svm_model = SVC(
    kernel="rbf",
    C=1,
    gamma="scale",
    probability=True,
    random_state=42
)

svm_model.fit(X_train_scaled, y_train)

"""**Evaluate SVM**"""

svm_predictions = svm_model.predict(X_test_scaled)

print("SVM Accuracy:", accuracy_score(y_test, svm_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, svm_predictions))

print("\nClassification Report:")
print(classification_report(y_test, svm_predictions))

"""   **SVM confusion matrix graph**"""

ConfusionMatrixDisplay.from_predictions(y_test, svm_predictions)
plt.title("SVM Confusion Matrix")
plt.show()

"""**3D SVM Visualization**"""

pca = PCA(n_components=3, random_state=42)

X_scaled_all = StandardScaler().fit_transform(X)
X_pca = pca.fit_transform(X_scaled_all)

X_pca_train, X_pca_test, y_pca_train, y_pca_test = train_test_split(
    X_pca,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

svm_3d = SVC(kernel="linear", C=1, random_state=42)
svm_3d.fit(X_pca_train, y_pca_train)

print("3D PCA SVM Accuracy:", accuracy_score(y_pca_test, svm_3d.predict(X_pca_test)))

"""**3D Decision Boundary Graph**"""

fig = plt.figure(figsize=(10, 7))
ax = fig.add_subplot(111, projection="3d")

ax.scatter(
    X_pca[:, 0],
    X_pca[:, 1],
    X_pca[:, 2],
    c=y,
    alpha=0.5,
    s=15
)

xx, yy = np.meshgrid(
    np.linspace(X_pca[:, 0].min(), X_pca[:, 0].max(), 20),
    np.linspace(X_pca[:, 1].min(), X_pca[:, 1].max(), 20)
)

w = svm_3d.coef_[0]
b = svm_3d.intercept_[0]

zz = -(w[0] * xx + w[1] * yy + b) / w[2]

ax.plot_surface(xx, yy, zz, alpha=0.3)

ax.set_xlabel("PCA Component 1")
ax.set_ylabel("PCA Component 2")
ax.set_zlabel("PCA Component 3")

plt.title("3D SVM Decision Boundary using PCA")
plt.show()

"""**Train basic XGBoost model**"""

xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    eval_metric="logloss",
    random_state=42,
    tree_method="hist",
    n_jobs=1
)

xgb_model.fit(X_train, y_train)

"""**Evaluate XGBoost**"""

xgb_predictions = xgb_model.predict(X_test)

print("XGBoost Accuracy:", accuracy_score(y_test, xgb_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_predictions))

print("\nClassification Report:")
print(classification_report(y_test, xgb_predictions))

"""**Confusion Matrix Graph XGBoost**"""

ConfusionMatrixDisplay.from_predictions(y_test, xgb_predictions)
plt.title("XGBoost Confusion Matrix")
plt.show()

"""**Tune XGBoost estimators and learning rate**"""

results = []

n_estimators_list = [50, 100, 150, 200, 300]
learning_rate_list = [0.01, 0.05, 0.1, 0.2, 0.3]

for n in n_estimators_list:
    for lr in learning_rate_list:

        model = XGBClassifier(
            n_estimators=n,
            learning_rate=lr,
            max_depth=3,
            eval_metric="logloss",
            random_state=42,
            tree_method="hist",
            n_jobs=1
        )

        model.fit(X_train, y_train)

        predictions = model.predict(X_test)
        probabilities = model.predict_proba(X_test)

        accuracy = accuracy_score(y_test, predictions)
        prediction_error = 1 - accuracy
        loss = log_loss(y_test, probabilities)

        results.append([n, lr, accuracy, prediction_error, loss])

results_df = pd.DataFrame(
    results,
    columns=["n_estimators", "learning_rate", "accuracy", "prediction_error", "log_loss"]
)

results_df

"""**Find best XGBoost results**"""

best_result = results_df.sort_values(by=["prediction_error", "log_loss"]).head(1)

best_result

"""**Train Final best XGBoost Model**"""

best_n = int(best_result["n_estimators"].values[0])
best_lr = float(best_result["learning_rate"].values[0])

best_xgb_model = XGBClassifier(
    n_estimators=best_n,
    learning_rate=best_lr,
    max_depth=3,
    eval_metric="logloss",
    random_state=42,
    tree_method="hist",
    n_jobs=1
)

best_xgb_model.fit(X_train, y_train)

best_xgb_predictions = best_xgb_model.predict(X_test)

print("Best XGBoost Accuracy:", accuracy_score(y_test, best_xgb_predictions))

print("\nBest XGBoost Confusion Matrix:")
print(confusion_matrix(y_test, best_xgb_predictions))

print("\nBest XGBoost Classification Report:")
print(classification_report(y_test, best_xgb_predictions))

"""**Prediction error by number of estimators**"""

for lr in learning_rate_list:
    temp = results_df[results_df["learning_rate"] == lr]
    plt.plot(temp["n_estimators"], temp["prediction_error"], marker="o", label=f"LR={lr}")

plt.title("XGBoost Prediction Error Optimization")
plt.xlabel("Number of Estimators")
plt.ylabel("Prediction Error")
plt.legend()
plt.show()

"""**Log loss by number of estimators**"""

for lr in learning_rate_list:
    temp = results_df[results_df["learning_rate"] == lr]
    plt.plot(temp["n_estimators"], temp["log_loss"], marker="o", label=f"LR={lr}")

plt.title("XGBoost Log Loss Optimization")
plt.xlabel("Number of Estimators")
plt.ylabel("Log Loss")
plt.legend()
plt.show()

"""**Feature Importance**"""

importance = pd.Series(
    best_xgb_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

importance.plot(kind="bar")
plt.title("Tuned XGBoost Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance Score")
plt.show()